// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.13.0
// source: api/hash.proto

package hashservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	H string `protobuf:"bytes,1,opt,name=h,proto3" json:"h,omitempty"`
}

func (x *Hash) Reset() {
	*x = Hash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hash_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hash) ProtoMessage() {}

func (x *Hash) ProtoReflect() protoreflect.Message {
	mi := &file_api_hash_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hash.ProtoReflect.Descriptor instead.
func (*Hash) Descriptor() ([]byte, []int) {
	return file_api_hash_proto_rawDescGZIP(), []int{0}
}

func (x *Hash) GetH() string {
	if x != nil {
		return x.H
	}
	return ""
}

type Strings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *Strings) Reset() {
	*x = Strings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hash_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Strings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Strings) ProtoMessage() {}

func (x *Strings) ProtoReflect() protoreflect.Message {
	mi := &file_api_hash_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Strings.ProtoReflect.Descriptor instead.
func (*Strings) Descriptor() ([]byte, []int) {
	return file_api_hash_proto_rawDescGZIP(), []int{1}
}

func (x *Strings) GetList() []string {
	if x != nil {
		return x.List
	}
	return nil
}

type Hashs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List    []*Hash `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Success bool    `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *Hashs) Reset() {
	*x = Hashs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hash_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hashs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hashs) ProtoMessage() {}

func (x *Hashs) ProtoReflect() protoreflect.Message {
	mi := &file_api_hash_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hashs.ProtoReflect.Descriptor instead.
func (*Hashs) Descriptor() ([]byte, []int) {
	return file_api_hash_proto_rawDescGZIP(), []int{2}
}

func (x *Hashs) GetList() []*Hash {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *Hashs) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_hash_proto protoreflect.FileDescriptor

var file_api_hash_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x14, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x0c,
	0x0a, 0x01, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x68, 0x22, 0x1d, 0x0a, 0x07,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x41, 0x0a, 0x05, 0x48,
	0x61, 0x73, 0x68, 0x73, 0x12, 0x1e, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x68, 0x61, 0x73, 0x68, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x38,
	0x0a, 0x0a, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2a, 0x0a, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12, 0x0d, 0x2e, 0x68, 0x61, 0x73,
	0x68, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x1a, 0x0b, 0x2e, 0x68, 0x61, 0x73, 0x68,
	0x2e, 0x48, 0x61, 0x73, 0x68, 0x73, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x68, 0x61, 0x73, 0x68,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_hash_proto_rawDescOnce sync.Once
	file_api_hash_proto_rawDescData = file_api_hash_proto_rawDesc
)

func file_api_hash_proto_rawDescGZIP() []byte {
	file_api_hash_proto_rawDescOnce.Do(func() {
		file_api_hash_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_hash_proto_rawDescData)
	})
	return file_api_hash_proto_rawDescData
}

var file_api_hash_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_hash_proto_goTypes = []interface{}{
	(*Hash)(nil),    // 0: hash.Hash
	(*Strings)(nil), // 1: hash.Strings
	(*Hashs)(nil),   // 2: hash.Hashs
}
var file_api_hash_proto_depIdxs = []int32{
	0, // 0: hash.Hashs.list:type_name -> hash.Hash
	1, // 1: hash.StringHash.CreateHash:input_type -> hash.Strings
	2, // 2: hash.StringHash.CreateHash:output_type -> hash.Hashs
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_hash_proto_init() }
func file_api_hash_proto_init() {
	if File_api_hash_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_hash_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_hash_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Strings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_hash_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hashs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_hash_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_hash_proto_goTypes,
		DependencyIndexes: file_api_hash_proto_depIdxs,
		MessageInfos:      file_api_hash_proto_msgTypes,
	}.Build()
	File_api_hash_proto = out.File
	file_api_hash_proto_rawDesc = nil
	file_api_hash_proto_goTypes = nil
	file_api_hash_proto_depIdxs = nil
}
